# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6bd629344e3f4435974777d6827e7dd50060578967d264c31775c9b327ff34dd974e4c892abc2712ddbdcca82c601823f10ebdff64771f076cec7eb8dd0fb5f

test:
  secret_key_base: e6690f81bb4d8a524fad5247b9bd23ab229cf178559ac802be3c11ba415c68aff7147f8ec7697f2738d6726a48b8be137711dc0b3abc87db729dcc27f68b097a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
